[project]
name = "iso4217parse"
version = "0.7.0"
description = "Parse currencies (symbols and codes) from and to ISO4217."
authors = [{ name = "Tammo Ippen", email = "tammo.ippen@posteo.de" }]
requires-python = ">=3.11,<4"
readme = "README.md"
license = "MIT"
keywords = [
    "iso4217",
    "currency",
    "parse",
    "symbol",
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.urls]
Homepage = "https://github.com/tammoippen/iso4217parse"
Repository = "https://github.com/tammoippen/iso4217parse"

[dependency-groups]
dev = [
    "coveralls",
    "iso3166",
    "mypy",
    "pytest",
    "pytest-cov",
    "ruff",
]
gen = ["lxml", "bs4", "iso3166", "dateparser", "requests"]

[tool.uv]
default-groups = "all"

[tool.pytest.ini_options]
addopts = ["--cov=iso4217parse", "--cov-branch", "--cov-report", "term-missing", "--cov-report", "html:cov_html", "--cov-report=xml:coverage.xml"]

[tool.flit.sdist]
include = ["tests/", "CHANGELOG.md"]

[build-system]
requires = ["flit_core >=4.0.2"]
build-backend = "flit_core.buildapi"
